GET http://localhost:3000/tasks
###
GET http://localhost:3000/tasks/6453b591560de262f2eaaf79
###
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title" : "Make a chicken dinner!"
}
###
DELETE http://localhost:3000/tasks/6453b591560de262f2eaaf79
###
PATCH http://localhost:3000/tasks/6453b591560de262f2eaaf79
Content-Type: application/json

{
  "title": "Make a sunday roast!"
}